djangolearning/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('music/', include('music.urls')),
    path('admin/', admin.site.urls),
]

music/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include,path
from . import views
app_name='music'

urlpatterns = [

    path('', views.index, name = 'index'),
    url(r'^([0-9]+)/$', views.detail, name = 'detail'),
    url(r'^([0-9]+)/favorite/$', views.favorite, name = 'favorite'),

]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=200)

    def __str__(self):
        return self.album_title + ' - ' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)


    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album
# Create your views here.


def index(request):
    all_albums = Album.objects.all()

    context = {'all_albums':all_albums}
    return render(request, 'music/index.html', context)

def detail(request, album_id):
    album=get_object_or_404(Album,pk=album_id)
    return render(request, 'music/detail.html',{'album':album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song=album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album':album,
            'error_message': 'You did not selected the valid song'
        })
    else:
        selected_song.is_favorite=True
        selected_song.save()
        return render(request,'music/detail.html', {'album':album})

music/templates/music/detail.html
<img src="#">
<h1>{{ album.album_title }}</h1>
<h1>{{ album.artist }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png"/>
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<nav class="navbar navbar-dark bg-primary">
    <div class="container-fluid"></div>
    <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>

    </div>

</nav>



{% if all_albums %}
    <h3>Here are all my albums</h3>

    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3>You don't have any albums</h3>
{% endif %}